[profile.default]
ffi = true
ast = true
build_info = true
src = "contracts"
out = "out"
extra_output = ["storageLayout"]
libs = ["lib"]
solc = "0.8.25"
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "./"}]
# evm_version = "shanghai"
[rpc_endpoints]
testnet = ""
# remappings = [
#     "@solmate-utils/=lib/solmate/src/utils/",
# ]



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options